version: '3.9'
services:
  nats:
    image: nats:1.4.1
    ports:
      - "4222:4222"
  proxy:
    build: projects-proxy
    image: fulib/fulib.org-projects-proxy
    ports:
      - "8080:80"
    networks:
      - projects
  keycloak:
    image: jboss/keycloak:12.0.4
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "24785:8080"
    restart: always
    volumes:
      - 'keycloak-data:/opt/jboss/keycloak/standalone/data/'
volumes:
  keycloak-data:
networks:
  projects:
