version: '3.9'
services:
  nats:
    image: nats:2
    restart: unless-stopped
    ports:
      - "4222:4222"
  proxy:
    build: projects-proxy
    image: fulib/fulib.org-projects-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - projects
  elasticsearch:
    image: elasticsearch:7.13.4
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
networks:
  projects:
