services:
  frontend:
    image: fulib/fulib.org-frontend
    build:
      context: frontend/
      args:
        CONFIGURATION: development
    ports:
      - '11340:80'
  nats:
    image: nats:2
    restart: unless-stopped
    ports:
      - "4222:4222"
  database:
    image: mongo:4
