name: CI/CD

on:
  - push

jobs:
  deployment:
    name: Deployment Setup
    runs-on: ubuntu-latest
    steps:
      - name: Set Deployment Options
        id: deployment
        run: |
          VERSION="${GITHUB_REF##*/}"
          case "$GITHUB_REF" in
            refs/heads/develop) NAMESPACE=dev ;;
            refs/heads/feat/projects) NAMESPACE=fulib-projects ;;
            refs/tags/v*) NAMESPACE=prod ;;
          esac
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=namespace::$NAMESPACE"
    outputs:
      version: ${{ steps.deployment.outputs.version }}
      namespace: ${{ steps.deployment.outputs.namespace }}
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    needs: [deployment]
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Cache PNPM Store
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            /.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: pnpm-${{ runner.os }}-
      - name: Install packages
        run: pnpm install
      - name: Build Angular
        run: pnpm build
      - name: Determine Deployment Readiness
        id: deployment
        if: needs.deployment.outputs.namespace
        run: echo "::set-output name=ready::true"
      - name: Build Angular again
        if: steps.deployment.outputs.ready
        run: pnpm build
      - name: Build the Docker Image
        if: steps.deployment.outputs.ready
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-frontend
          image_tag: ${{ needs.deployment.outputs.version }}
          context: frontend/
      - name: Deploy to Rancher
        if: steps.deployment.outputs.ready
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: ${{ needs.deployment.outputs.namespace }}
          deployment: fulib-frontend
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/fulib/fulib.org-frontend:${{ needs.deployment.outputs.version }}
  backend:
    name: Backend
    runs-on: ubuntu-latest
    needs: [deployment]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
          java-package: jdk
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('backend/*.gradle') }}
          restore-keys: gradle-${{ runner.os }}-
      - name: Build with Gradle
        run: ./gradlew :backend:build && ./gradlew --stop
      - name: Determine Deployment Readiness
        id: deployment
        if: needs.deployment.outputs.namespace
        run: echo "::set-output name=ready::true"
      - name: Build the Backend Docker Image
        if: steps.deployment.outputs.ready
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-backend
          image_tag: ${{ needs.deployment.outputs.version }}
          context: backend/
      - name: Deploy the Backend to Rancher
        if: steps.deployment.outputs.ready
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: ${{ needs.deployment.outputs.namespace }}
          deployment: fulib-backend
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/fulib/fulib.org-backend:${{ needs.deployment.outputs.version }}
  assignments-service:
    name: Assignments Service
    runs-on: ubuntu-latest
    needs: [deployment]
    defaults:
      run:
        working-directory: services
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-assignments-service
          image_tag: ${{ needs.deployment.outputs.version }}
          build_extra_args: "--build-arg=SERVICE=assignments"
          context: services/
      - name: Deploy to Rancher
        if: needs.deployment.outputs.namespace
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: ${{ needs.deployment.outputs.namespace }}
          deployment: fulib-assignments-service
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/fulib/fulib.org-assignments-service:${{ needs.deployment.outputs.version }}
  projects-service:
    name: Projects Service
    runs-on: ubuntu-latest
    needs: [deployment]
    defaults:
      run:
        working-directory: services
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-projects-service
          image_tag: ${{ needs.deployment.outputs.version }}
          build_extra_args: "--build-arg=SERVICE=projects"
          context: services/
      - name: Deploy to Rancher
        if: needs.deployment.outputs.namespace
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: ${{ needs.deployment.outputs.namespace }}
          deployment: fulib-projects-service
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/fulib/fulib.org-projects-service:${{ needs.deployment.outputs.version }}
  projects-container:
    name: Projects Container
    runs-on: ubuntu-latest
    needs: [deployment]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
          java-package: jdk
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('projects/*.gradle') }}
          restore-keys: gradle-${{ runner.os }}-
      - name: Build with Gradle
        run: ./gradlew :projects:build && ./gradlew --stop
      - name: Build the Project Container Docker Image
        if: needs.deployment.outputs.namespace
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-projects
          image_tag: ${{ needs.deployment.outputs.version }}
          context: projects/
  projects-runtime:
    name: Projects Runtime
    runs-on: ubuntu-latest
    needs: [deployment, projects-container]
    if: needs.deployment.outputs.namespace
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build the Projects Proxy Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-projects-proxy
          image_tag: ${{ needs.deployment.outputs.version }}
          context: projects-proxy/
      - name: Build the Projects Runtime Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-projects-runtime
          image_tag: ${{ needs.deployment.outputs.version }}
          context: projects-runtime/
      - name: Deploy the Projects Runtime to Rancher
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: ${{ needs.deployment.outputs.namespace }}
          deployment: fulib-projects-runtime
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/fulib/fulib.org-projects-runtime:${{ needs.deployment.outputs.version }}
