name: Deploy Frontend

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths:
      - 'frontend/**'

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for git describe
      - name: Set Deployment Options
        id: deployment
        run: ./.github/workflows/deploy.sh
      - name: Build the Docker Image
        uses: whoan/docker-build-with-cache-action@v6
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-frontend
          image_tag: ${{ steps.deployment.outputs.tag }}
          context: frontend/
      - name: Deploy to Rancher
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: ${{ secrets.NAMESPACE }}
          deployment: fulib-frontend
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/fulib/fulib.org-frontend:${{ steps.deployment.outputs.tag }}
