name: Deploy

on:
  push:
    branches:
      - develop
    tags:
      - v*

jobs:
  deployment:
    name: Deployment Setup
    runs-on: ubuntu-latest
    steps:
      - name: Set Deployment Options
        id: deployment
        run: |
          VERSION="${GITHUB_REF##*/}"
          case "$GITHUB_REF" in
            refs/heads/develop) NAMESPACE=dev ;;
            refs/tags/v*) NAMESPACE=prod ;;
          esac
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.deployment.outputs.version }}
      namespace: ${{ steps.deployment.outputs.namespace }}
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    needs: [ deployment ]
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-frontend
          image_tag: ${{ needs.deployment.outputs.version }}
          context: frontend/
      - name: Deploy to Rancher
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: ${{ needs.deployment.outputs.namespace }}
          deployment: fulib-frontend
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/fulib/fulib.org-frontend:${{ needs.deployment.outputs.version }}
  backend:
    name: Backend
    runs-on: ubuntu-latest
    needs: [ deployment ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build the Backend Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-backend
          image_tag: ${{ needs.deployment.outputs.version }}
          context: backend/
          build_extra_args: --build-arg VERSION=${{ needs.deployment.outputs.version }}
      - name: Deploy the Backend to Rancher
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: ${{ needs.deployment.outputs.namespace }}
          deployment: fulib-backend
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/fulib/fulib.org-backend:${{ needs.deployment.outputs.version }}
  services:
    name: ${{ matrix.service}} Service
    runs-on: ubuntu-latest
    needs: [ deployment ]
    defaults:
      run:
        working-directory: services
    strategy:
      matrix:
        service:
          - projects
          - assignments
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-${{ matrix.service }}-service
          image_tag: ${{ needs.deployment.outputs.version }}
          build_extra_args: --build-arg=SERVICE=${{ matrix.service }}
          context: services/
          push_image_and_stages: ${{ !!needs.deployment.outputs.namespace }}
      - name: Deploy to Rancher
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: ${{ needs.deployment.outputs.namespace }}
          deployment: fulib-${{ matrix.service }}-service
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/fulib/fulib.org-${{ matrix.service }}-service:${{ needs.deployment.outputs.version }}
  projects-images:
    name: Projects Images
    runs-on: ubuntu-latest
    needs: [ deployment ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Code Server Base Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: registry.uniks.de/fulib/code-server-base
          context: projects/
          dockerfile: base/Dockerfile
          push_image_and_stages: ${{ !!needs.deployment.outputs.namespace }}
      - name: Build the Projects code-server Images
        working-directory: projects
        run: node build-all.mjs
  projects-proxy:
    name: Projects Proxy
    runs-on: ubuntu-latest
    needs: [ deployment ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the Projects Proxy Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-projects-proxy
          image_tag: ${{ needs.deployment.outputs.version }}
          context: projects/
          dockerfile: proxy/Dockerfile
          push_image_and_stages: ${{ !!needs.deployment.outputs.namespace }}
  projects-runtime:
    name: Projects Runtime
    runs-on: ubuntu-latest
    needs: [ deployment ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the Projects Runtime Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: fulib/fulib.org-projects-runtime
          image_tag: ${{ needs.deployment.outputs.version }}
          context: projects/
          dockerfile: runtime/Dockerfile
          push_image_and_stages: ${{ !!needs.deployment.outputs.namespace }}
  projects-deploy:
    name: Projects Deployment
    runs-on: ubuntu-latest
    needs: [ deployment, projects-images, projects-proxy, projects-runtime ]
    steps:
      - name: Deploy the Projects Runtime to Rancher
        uses: sekassel-research/actions-rancher-update@v3.0.0
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: ${{ needs.deployment.outputs.namespace }}
          deployment: fulib-projects-runtime
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/fulib/fulib.org-projects-runtime:${{ needs.deployment.outputs.version }}
