name: Java CI

on:
   - push

jobs:
   build:
      name: Java ${{ matrix.java }} on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}-latest
      strategy:
         matrix:
            java:
               - 8
               - 11
            os:
               - ubuntu
               - windows
      steps:
         -  name: Checkout
            uses: actions/checkout@v2
            with:
               fetch-depth: 0
         -  name: Set up JDK ${{ matrix.java }}
            uses: actions/setup-java@v1
            with:
               java-version: ${{ matrix.java }}
               java-package: jdk
         -  name: Set up Node 14
            uses: actions/setup-node@v1
            with:
               node-version: '14'
         -  name: Install PNPM
            run: npm install -g pnpm
         -  name: Install Angular CLI
            run: pnpm install -g @angular/cli
         -  name: Setup Angular CLI to use PNPM
            run: ng config -g cli.packageManager pnpm
         -  name: Cache Gradle packages
            uses: actions/cache@v2
            with:
               path: ~/.gradle/caches
               key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
               restore-keys: ${{ runner.os }}-gradle
         -  name: Cache PNPM Store
            uses: actions/cache@v2
            with:
               path: ~/.pnpm-store
               key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
               restore-keys: ${{ runner.os }}-pnpm
         -  name: Build with Gradle
            run: ./gradlew build
