name: Test Backend

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Test Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: backend/
